
version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "elasticsearch"
    volumes:
      - .:/code
      - ./towhee:/root/.towhee
      - ./cache/torch:/root/.cache/torch
    environment:
      # FLASK_ENV: development
      FLASK_ENV: production
  elasticsearch:
    image: "elasticsearch:7.16.2"
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'

